README.md の構成を他の SDK のサンプル集と合わせるようにしました
shiguredo/sora-android-sdk-samples pull request #21
Opened 2021-03-10 03:05 UTC by torikizi

- サンプルの紹介を追加しました
- 不要なリンクや誤りと思われる記載を削除しました

2021-03-10 03:10 UTC, enm10k requested changes
レビューしました

2021-03-10 03:10 UTC, enm10k commented on README.md
> +### VoiceChatRoom
VideoChatRoom が2つある気がします

2021-03-10 03:10 UTC, enm10k commented on README.md
> +ビデオチャットのデモです。複数人でのグループチャットやサイマルキャストも利用可能です。
ビデオチャットではサイマルキャストは利用できないと思います
サイマルキャストの確認は、サイマルキャストという別の画面で行なえます

2021-03-10 03:11 UTC, enm10k commented on README.md
> +最新 Releases をダウンロードしてください。
ここを releases へのリンクにしてあげると良いかもしれません

2021-03-10 03:13 UTC, shino commented on README.md
> +ビデオチャットのデモです。複数人でのグループチャットやサイマルキャストも利用可能です。
サイマルキャストも入れちゃいましょう!

2021-03-10 12:24 UTC, torikizi commented on README.md
> +最新 Releases をダウンロードしてください。
ありがとうございます。リンクに修正します。

2021-03-10 12:25 UTC, torikizi commented on README.md
> +ビデオチャットのデモです。複数人でのグループチャットやサイマルキャストも利用可能です。
参考にしたバージョンが 2020.1 だったために最新の機能一覧になっておりませんでした。修正します。

2021-03-11 00:55 UTC, shino approved these changes
:+1:

2021-03-11 01:35 UTC, enm10k commented
@torikizi 
修正を確認しました
ありがとうございました

2021-03-11 02:32 UTC, torikizi commented
レビューありがとうございました。
マージします。

2021-03-11 02:33 UTC, merged